[workspace.package]
version = "2.4.6"
authors = [
    "Dietmar Maurer <dietmar@proxmox.com>",
    "Dominik Csapak <d.csapak@proxmox.com>",
    "Christian Ebner <c.ebner@proxmox.com>",
    "Fabian Grünbichler <f.gruenbichler@proxmox.com>",
    "Stefan Reiter <s.reiter@proxmox.com>",
    "Thomas Lamprecht <t.lamprecht@proxmox.com>",
    "Wolfgang Bumiller <w.bumiller@proxmox.com>",
    "Proxmox Support Team <support@proxmox.com>",
]
edition = "2021"
license = "AGPL-3"
repository = "git://git.proxmox.com/?p=proxmox-backup.git"

[package]
name = "proxmox-backup"
description = "Proxmox Backup"
homepage = "https://www.proxmox.com"

version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

exclude = [ "build", "debian", "tests/catar_data/test_symlink/symlink1"]

[workspace]
members = [
    "pbs-api-types",
    "pbs-buildcfg",
    "pbs-client",
    "pbs-config",
    "pbs-datastore",
    "pbs-fuse-loop",
    "pbs-key-config",
    "pbs-pxar-fuse",
    "pbs-tape",
    "pbs-tools",

    "proxmox-backup-banner",
    "proxmox-backup-client",
    "proxmox-file-restore",
    "proxmox-restore-daemon",
    "proxmox-rrd",

    "pxar-bin",
]

[lib]
name = "proxmox_backup"
path = "src/lib.rs"

[workspace.dependencies]
# proxmox workspace
proxmox-async = { version = "0.4", git =  "https://github.com/JulienMalka/proxmox-rs.git" }
proxmox-auth-api = { version = "0.1", git = "https://github.com/JulienMalka/proxmox-rs.git"}
proxmox-borrow = { version = "1", git = "https://github.com/JulienMalka/proxmox-rs.git" }
proxmox-compression = { version = "0.1.1", git =  "https://github.com/JulienMalka/proxmox-rs.git" }
proxmox-fuse = { version = "0.1.3", git =  "https://github.com/proxmox/proxmox-fuse-rs.git" }
proxmox-http = { version = "0.8.0", features = [ "client", "http-helpers", "websocket" ],  git =  "https://github.com/JulienMalka/proxmox-rs.git"  } # see below
proxmox-io = { version = "1.0.1", git = "https://github.com/JulienMalka/proxmox-rs.git" } # tools and client use "tokio" feature
proxmox-lang = { version = "1.1", git = "https://github.com/JulienMalka/proxmox-rs.git" }
proxmox-ldap = { version = "0.1", git = "https://github.com/JulienMalka/proxmox-rs.git"}
proxmox-metrics = { version = "0.2", git = "https://github.com/JulienMalka/proxmox-rs.git"}

proxmox-rest-server = { version = "0.3.0", features = [ "templates" ], git = "https://github.com/JulienMalka/proxmox-rs.git"  }
proxmox-router = { version = "1.3.1", default_features = false, git = "https://github.com/JulienMalka/proxmox-rs.git" }
proxmox-schema = { version = "1.3.6", git = "https://github.com/JulienMalka/proxmox-rs.git" }
proxmox-section-config = { version = "1", git = "https://github.com/JulienMalka/proxmox-rs.git" }
proxmox-serde = { version = "0.1.1", git = "https://github.com/JulienMalka/proxmox-rs.git"  }
proxmox-shared-memory = { version = "0.2.3", git = "https://github.com/JulienMalka/proxmox-rs.git" }
proxmox-sortable-macro = { version = "0.1.2", git = "https://github.com/JulienMalka/proxmox-rs.git" }
proxmox-subscription = { version = "0.3", features = [ "api-types" ], git = "https://github.com/JulienMalka/proxmox-rs.git"  }
proxmox-sys = { version = "0.4.2", git = "https://github.com/JulienMalka/proxmox-rs.git" }
proxmox-tfa = { version = "4", features = [ "api", "api-types" ], git = "https://github.com/JulienMalka/proxmox-rs.git"  }
proxmox-time = { version = "1.1.2", git = "https://github.com/JulienMalka/proxmox-rs.git"}
proxmox-uuid = { version = "1", git = "https://github.com/JulienMalka/proxmox-rs.git"}

# other proxmox crates
pathpatterns = {version = "0.1.2", git = "https://github.com/proxmox/pathpatterns-rs.git", rev = "ca9b0e38e36e7d677f39d253004483e57419dc1e" }
proxmox-acme-rs = { version = "0.4", git =  "https://github.com/proxmox/proxmox-acme-rs.git", rev = "6e1e835739012d4b4ce75938e886ed9c7f983ef2" }
proxmox-apt = { version = "0.9.4", git =  "https://github.com/JulienMalka/proxmox-rs.git" }
proxmox-openid = { version = "0.9.9", git = "https://github.com/JulienMalka/proxmox-rs.git"}
pxar = { version = "0.10.2", git = "https://github.com/proxmox/pxar.git", rev = "d33f63a730823391f122cbf4c2d09edd225b5a97" }

# PBS workspace
pbs-api-types = { path = "pbs-api-types" }
pbs-buildcfg = { path = "pbs-buildcfg" }
pbs-client = { path = "pbs-client" }
pbs-config = { path = "pbs-config" }
pbs-datastore = { path = "pbs-datastore" }
pbs-fuse-loop = { path = "pbs-fuse-loop" }
pbs-key-config = { path = "pbs-key-config" }
pbs-pxar-fuse = { path = "pbs-pxar-fuse" }
pbs-tape = { path = "pbs-tape" }
pbs-tools = { path = "pbs-tools" }
proxmox-rrd = { path = "proxmox-rrd" }

# regular crates
anyhow = "1.0"
apt-pkg-native = "0.3.2"
base64 = "0.13"
bitflags = "1.2.1"
bytes = "1.0"
cidr = "0.2.1"
crc32fast = "1"
crossbeam-channel = "0.5"
endian_trait = { version = "0.6", features = ["arrays"] }
env_logger = "0.9"
flate2 = "1.0"
foreign-types = "0.3"
futures = "0.3"
h2 = { version = "0.3", features = [ "stream" ] }
handlebars = "3.0"
hex = "0.4.3"
http = "0.2"
hyper = { version = "0.14", features = [ "full" ] }
lazy_static = "1.4"
libc = "0.2"
log = "0.4.17"
nix = "0.26.1"
nom = "7"
num-traits = "0.2"
once_cell = "1.3.1"
openssl = "0.10.40"
pam = "0.7"
pam-sys = "0.5"
percent-encoding = "2.1"
pin-project-lite = "0.2"
regex = "1.5.5"
rustyline = "9"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11.1"
serde_json = "1.0"
serde_plain = "1"
siphasher = "0.3"
syslog = "6"
tar = "0.4"
termcolor = "1.1.2"
thiserror = "1.0"
tokio = "1.6"
tokio-openssl = "0.6.1"
tokio-stream = "0.1.0"
tokio-util = { version = "0.7", features = [ "io" ] }
tower-service = "0.3.0"
udev = "0.4"
url = "2.1"
walkdir = "2"
xdg = "2.2"
zstd = { version = "0.6", features = [ "bindgen" ] }

[dependencies]
anyhow.workspace = true
apt-pkg-native.workspace = true
base64.workspace = true
bitflags.workspace = true
bytes.workspace = true
cidr.workspace = true
crc32fast.workspace = true
crossbeam-channel.workspace = true
endian_trait.workspace = true
flate2.workspace = true
futures.workspace = true
h2.workspace = true
handlebars.workspace = true
hex.workspace = true
http.workspace = true
hyper.workspace = true
lazy_static.workspace = true
libc.workspace = true
log.workspace = true
nix.workspace = true
nom.workspace = true
num-traits.workspace = true
once_cell.workspace = true
openssl.workspace = true
pam-sys.workspace = true
pam.workspace = true
percent-encoding.workspace = true
regex.workspace = true
rustyline.workspace = true
serde.workspace = true
serde_json.workspace = true
siphasher.workspace = true
syslog.workspace = true
termcolor.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = [ "fs", "io-util", "io-std", "macros", "net", "parking_lot", "process", "rt", "rt-multi-thread", "signal", "time" ] }
tokio-openssl.workspace = true
tokio-stream.workspace = true
tokio-util = { workspace = true, features = [ "codec" ] }
tower-service.workspace = true
udev.workspace = true
url.workspace = true
walkdir.workspace = true
xdg.workspace = true
zstd.workspace = true

#valgrind_request = { git = "https://github.com/edef1c/libvalgrind_request", version = "1.1.0", optional = true }

proxmox-async.workspace = true
proxmox-auth-api = { workspace = true, features = [ "api", "pam-authenticator" ] }
proxmox-compression.workspace = true
proxmox-http = { workspace = true, features = [ "client-trait", "proxmox-async", "rate-limited-stream" ] } # pbs-client doesn't use these
proxmox-io.workspace = true
proxmox-lang.workspace = true
proxmox-ldap.workspace = true
proxmox-metrics.workspace = true
proxmox-rest-server = { workspace = true, features = [ "rate-limited-stream" ] }
proxmox-router = { workspace = true, features = [ "cli", "server"] }
proxmox-schema = { workspace = true, features = [ "api-macro" ] }
proxmox-section-config.workspace = true
proxmox-serde = { workspace = true, features = [ "serde_json" ] }
proxmox-shared-memory.workspace = true
proxmox-sortable-macro.workspace = true
proxmox-subscription.workspace = true
proxmox-sys = { workspace = true, features = [ "timer" ] }
proxmox-tfa.workspace = true
proxmox-time.workspace = true
proxmox-uuid.workspace = true

pathpatterns.workspace = true
proxmox-acme-rs.workspace = true
proxmox-apt.workspace = true
proxmox-openid.workspace = true
pxar.workspace = true

pbs-api-types.workspace = true
pbs-buildcfg.workspace = true
pbs-client.workspace = true
pbs-config.workspace = true
pbs-datastore.workspace = true
pbs-key-config.workspace = true
pbs-tape.workspace = true
pbs-tools.workspace = true
proxmox-rrd.workspace = true

# Local path overrides
# NOTE: You must run `cargo update` after changing this for it to take effect!
[patch.crates-io]
#proxmox-acme-rs = { path = "../proxmox-acme-rs" }
#proxmox-async = { path = "../proxmox/proxmox-async" }
#proxmox-auth-api = { path = "../proxmox/proxmox-auth-api" }
#proxmox-borrow = { path = "../proxmox/proxmox-borrow" }
#proxmox-compression = { path = "../proxmox/proxmox-compression" }
#proxmox-fuse = { path = "../proxmox-fuse" }
#proxmox-http = { path = "../proxmox/proxmox-http" }
#proxmox-io = { path = "../proxmox/proxmox-io" }
#proxmox-lang = { path = "../proxmox/proxmox-lang" }
#proxmox-rest-server = { path = "../proxmox/proxmox-rest-server" }
#proxmox-router = { path = "../proxmox/proxmox-router" }
#proxmox-schema = { path = "../proxmox/proxmox-schema" }
#proxmox-section-config = { path = "../proxmox/proxmox-section-config" }
#proxmox-serde = { path = "../proxmox/proxmox-serde" }
#proxmox-shared-memory = { path = "../proxmox/proxmox-shared-memory" }
#proxmox-subscription = { path = "../proxmox/proxmox-subscription" }
#proxmox-sys = { path = "../proxmox/proxmox-sys" }
#proxmox-tfa = { path = "../proxmox/proxmox-tfa" }
#proxmox-time = { path = "../proxmox/proxmox-time" }
#proxmox-uuid = { path = "../proxmox/proxmox-uuid" }

#proxmox-apt = { path = "../proxmox-apt" }
#proxmox-openid = { path = "../proxmox-openid-rs" }

#pxar = { path = "../pxar" }

[features]
default = []
#valgrind = ["valgrind_request"]
