[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pve-update"
version = "1.0.0"
description = "Updater for Proxmox-NixOS derivations"
authors = [
    {name = "Julien Malka"},
    {name = "Camille Mondon"}
]
license = {text = "MIT"}
requires-python = ">=3.10"
dependencies = [
    "aiohttp",
    "beautifulsoup4",
    "python-debian",
]

[project.scripts]
pve-update = "pve_update.cli:main"

[tool.setuptools.package-data]
"pve_update" = ["mappings.json"]
